### ISSUE TITLE
Using Gedmo sluggable behaviour with Prezent translatable

### ISSUE THREAD

**Issue by ghost** [Prezent/doctrine-translatable#1]
Hello, I am trying to get Prezent package working with a2lix translation. I am also using Gedmo sluggable behaviour which expects (sluggable) fields in the same class, but Prezent's translatable behaviour requires these fields to be moved to the translation class. Is it possible to use both? Or should I just stick to Gedmo's behaviours then?

**Comment by nomack84** [comment]
@sandermarechal I'm trying to use this in my project together with the gedmo sluggable behavior. When I create the entity with the default locale the slug is generated without problems, but when I switch to another language and change the the `name` field, which is the one I use for the slug, it doesn't update to the new locale. I'd like to have a different slug per language,  but for some reason isn't working. I think maybe the sluggable listener is not beign executed. 
Do you have any suggestions to solve this?
Thanks in advance!

**Comment by nomack84** [comment]
Sorry! It's working fine. It seems that I already need to sleep.
