### ISSUE TITLE
Yaml Mapping

### ISSUE THREAD

**Issue by ghanbari** [Prezent/doctrine-translatable#23]
I use yaml driver & map my entities as [yaml mapping](https://github.com/Prezent/doctrine-translatable/blob/master/doc/yaml-mapping.md)
but that no want work and i must use annotation.

> [Prezent\Doctrine\Translatable\Mapping\MappingException]     
   No translations specified for Anar\EngineBundle\Entity\Blog

**Comment by sandermarechal** [comment]
Yaml mapping is fully supported in since version 1.0
