### ISSUE TITLE
Using Iterate to process records on entity using translatable breaks with 500 error

### ISSUE THREAD

**Issue by ravindrakhokharia** [Prezent/doctrine-translatable#26]
Using Iterate to process records on entity using translatable breaks with 500 error
Error details are below. 
`Iterate with fetch join in class Prolix\ProjectBundle\Entity\ProjectTranslation using association translatable not allowed.`

We do have an entity holding millions of records, and iterate seems to be best for us to process the data, while we face this specific issue to fetch the translated data from the translation entity when joining in the query builder. 

Looking forward for any helps.

**Comment by sandermarechal** [comment]
You cannot use a FETCH JOIN with iteration in Doctrine. This is not specific to doctrine-translatable but related to Doctrine in general. To work around it, do not fetch-join the translations. The downside of that is that it will trigger an SQL SELECT for every row you iterate over.

For more information on why this is impossible, see https://github.com/doctrine/doctrine2/issues/2410
